language: java
notifications:
  hipchat:
    rooms:
      secure: ZiSyGwuy09O35VDhaUUtAIg3Feqx1vcmustxIEGL32+W6Dbw/UjhLWXsQofgPN0EFXcwpe9R7IyolYECQGBPrh75ftgnRZ7NOYdli3bdcudhLFLeiOvtP57274BWx+rMAOA8sk4CDvV/keToqxJlZ2RLSBoWGK/qwjtu0oP/jizuZ1BiFvOSppW7pj189lCidJdoRwpnr2/Ee4j9A0iTSmWRztriwMvfvL1Euyr8PP8xVKgypKKXtOT9kcl22k8T9dl35ps/D/FK/qhGXJEFjpSo2a1XniaQiw5zNr1m4ACrt7lChyHeKZYRHZD7A706OxAdkgzch33OcIi5IFpH7QtEDGUhWclaA7j3D48w9cJ8SP5RNOoxQ/kKso7Q9EQ+6Ism6rGr6R62KWUbCTM2/+cntOVJ97nzL9GOLOOt+YFLbBjLyPMEdj0xrw+CSVtmfNzJ6rT6MeXbhwSvRm3mB31mDHBE0fmMdHvr6ZEo76b169QSfdR6C4Di5dENrsMzobiL83T6pPksHweTdoTFfyx3Wk9rkp2iwWrb8saZOKm9H9ZwFLRhNbU3stj6LVjtZJArf3aAwLFlIqgGWnDL2HH7O01lXFXtZyJ+licNMWasOyCV4uP75ZHMIA6/v9V5UNCUNTdhE7vHRJbWmXQz+WNb+OlNqQcv0mc3nFADXkQ=
    on_success: always
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: LiAHufqUbsV6Qv0XWwiDx90wDXsbf4+36I349/wx91d2hSZBgkaqPgDdLwLXPIP9ViXOx/agkV/C9Dmm3jPQSSczCwlFGoKfrWLKyEnOrVDnZnNa/EtZi+odAplfBO4sB+m9KAng0X5NWU+qeXB4mFD5+uI9gi5GJfhDoAcpu7yVKJt6Ukyf/ars3P52bfCqVN0ockwC3GcUCsJM5uFM71TPmFK5G4ir+C7Z3GEtAezJqCuNitnK6e0PMIwdnnH0cEV2xNyjKV5ikPs8/GgI/oXKSSVWQAoL+948XSeUNqBQNInrXA/6anskN07+4QIW65WL5KA3dLyZzkerhi1SD/W5AVl/2BupYu/sw8zEH0ffyLK6Tq5SIb34N4MtVy805FslYpnMGYH+1rZDq2vBMmGK3mhCxyuyLaC5eLfc7KeH+ZczjS5+hfUYXRiYMfPQyo+k9VPX693H5ImwzZ6JIApQJlpGSdhHIGDw+Bz2QCEzRi5yvi4VDwy5HorUHblAcrZxvN5afFx9AO3w6IeEuoVxEzibB9Qm26IBnj4RJ8syAXJDWqdZ9J4X1Hp5ePV37+fPVXwzN+Lrdu7fy5AZCmQU6JaQ80ualnjwzeKSuHKFYNO3GIKOSDFh7mPEg97NYSMFk6B3Nsr9+trs4ADBjTJHQUrNfj6fzw5Gl3vwFQM=
  file: build/libs/xlr-bitbucket-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: xebialabs-community/xlr-bitbucket-plugin
